changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'fix'
        - 'bug'
    - title: '📚 Documentation'
      label: 'documentation'
  exclude:
    labels:
      - 'skip-changelog'
